//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAgent.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartAgentDbEntities : DbContext
    {
        public SmartAgentDbEntities()
            : base("name=SmartAgentDbEntities")
        {
    		OnContextCreated(); 
        }
    	partial void OnContextCreated(); 
    
       // protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
            //throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    }
}
